# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conversion.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='conversion.proto',
  package='blockchain',
  syntax='proto2',
  serialized_pb=_b('\n\x10\x63onversion.proto\x12\nblockchain\"U\n\x17SignatureRequestMessage\x12\x12\n\nidentifier\x18\x01 \x02(\r\x12&\n\x08\x63ontract\x18\x02 \x02(\x0b\x32\x14.blockchain.Contract\"V\n\x18SignatureResponseMessage\x12\x12\n\nidentifier\x18\x01 \x02(\r\x12&\n\x08\x63ontract\x18\x02 \x02(\x0b\x32\x14.blockchain.Contract\"9\n\x0f\x43ontractMessage\x12&\n\x08\x63ontract\x18\x01 \x02(\x0b\x32\x14.blockchain.Contract\"\'\n\x13\x42lockRequestMessage\x12\x10\n\x08\x62lock_id\x18\x01 \x02(\x0c\"0\n\x0c\x42lockMessage\x12 \n\x05\x62lock\x18\x01 \x02(\x0b\x32\x11.blockchain.Block\"Y\n\x17TraversalRequestMessage\x12\x12\n\nidentifier\x18\x01 \x02(\r\x12\x13\n\x0b\x63ontract_id\x18\x02 \x02(\x0c\x12\x15\n\rcontract_type\x18\x03 \x01(\r\"V\n\x18TraversalResponseMessage\x12\x12\n\nidentifier\x18\x01 \x02(\r\x12&\n\x08\x63ontract\x18\x02 \x01(\x0b\x32\x14.blockchain.Contract\"\xad\x01\n\x08\x43ontract\x12\x15\n\rprevious_hash\x18\x01 \x02(\x0c\x12\x17\n\x0f\x66rom_public_key\x18\x02 \x02(\x0c\x12\x16\n\x0e\x66rom_signature\x18\x03 \x02(\x0c\x12\x15\n\rto_public_key\x18\x04 \x02(\x0c\x12\x14\n\x0cto_signature\x18\x05 \x02(\x0c\x12\x10\n\x08\x64ocument\x18\x06 \x02(\x0c\x12\x0c\n\x04type\x18\x07 \x02(\r\x12\x0c\n\x04time\x18\x08 \x02(\r\"\xb6\x01\n\x05\x42lock\x12\x15\n\rprevious_hash\x18\x01 \x02(\x0c\x12\x18\n\x10merkle_root_hash\x18\x02 \x02(\x0c\x12\x19\n\x11target_difficulty\x18\x03 \x02(\x0c\x12\x0f\n\x07\x63reator\x18\x04 \x02(\x0c\x12\x19\n\x11\x63reator_signature\x18\x05 \x02(\x0c\x12\x0c\n\x04time\x18\x06 \x02(\r\x12\'\n\tcontracts\x18\x07 \x03(\x0b\x32\x14.blockchain.Contract')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SIGNATUREREQUESTMESSAGE = _descriptor.Descriptor(
  name='SignatureRequestMessage',
  full_name='blockchain.SignatureRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='blockchain.SignatureRequestMessage.identifier', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contract', full_name='blockchain.SignatureRequestMessage.contract', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=117,
)


_SIGNATURERESPONSEMESSAGE = _descriptor.Descriptor(
  name='SignatureResponseMessage',
  full_name='blockchain.SignatureResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='blockchain.SignatureResponseMessage.identifier', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contract', full_name='blockchain.SignatureResponseMessage.contract', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=205,
)


_CONTRACTMESSAGE = _descriptor.Descriptor(
  name='ContractMessage',
  full_name='blockchain.ContractMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contract', full_name='blockchain.ContractMessage.contract', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=264,
)


_BLOCKREQUESTMESSAGE = _descriptor.Descriptor(
  name='BlockRequestMessage',
  full_name='blockchain.BlockRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_id', full_name='blockchain.BlockRequestMessage.block_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=305,
)


_BLOCKMESSAGE = _descriptor.Descriptor(
  name='BlockMessage',
  full_name='blockchain.BlockMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block', full_name='blockchain.BlockMessage.block', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=355,
)


_TRAVERSALREQUESTMESSAGE = _descriptor.Descriptor(
  name='TraversalRequestMessage',
  full_name='blockchain.TraversalRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='blockchain.TraversalRequestMessage.identifier', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contract_id', full_name='blockchain.TraversalRequestMessage.contract_id', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contract_type', full_name='blockchain.TraversalRequestMessage.contract_type', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=446,
)


_TRAVERSALRESPONSEMESSAGE = _descriptor.Descriptor(
  name='TraversalResponseMessage',
  full_name='blockchain.TraversalResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='blockchain.TraversalResponseMessage.identifier', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contract', full_name='blockchain.TraversalResponseMessage.contract', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=534,
)


_CONTRACT = _descriptor.Descriptor(
  name='Contract',
  full_name='blockchain.Contract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='previous_hash', full_name='blockchain.Contract.previous_hash', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='from_public_key', full_name='blockchain.Contract.from_public_key', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='from_signature', full_name='blockchain.Contract.from_signature', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to_public_key', full_name='blockchain.Contract.to_public_key', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to_signature', full_name='blockchain.Contract.to_signature', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='document', full_name='blockchain.Contract.document', index=5,
      number=6, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='blockchain.Contract.type', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='blockchain.Contract.time', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=537,
  serialized_end=710,
)


_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='blockchain.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='previous_hash', full_name='blockchain.Block.previous_hash', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='merkle_root_hash', full_name='blockchain.Block.merkle_root_hash', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_difficulty', full_name='blockchain.Block.target_difficulty', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='creator', full_name='blockchain.Block.creator', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='creator_signature', full_name='blockchain.Block.creator_signature', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='blockchain.Block.time', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contracts', full_name='blockchain.Block.contracts', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=713,
  serialized_end=895,
)

_SIGNATUREREQUESTMESSAGE.fields_by_name['contract'].message_type = _CONTRACT
_SIGNATURERESPONSEMESSAGE.fields_by_name['contract'].message_type = _CONTRACT
_CONTRACTMESSAGE.fields_by_name['contract'].message_type = _CONTRACT
_BLOCKMESSAGE.fields_by_name['block'].message_type = _BLOCK
_TRAVERSALRESPONSEMESSAGE.fields_by_name['contract'].message_type = _CONTRACT
_BLOCK.fields_by_name['contracts'].message_type = _CONTRACT
DESCRIPTOR.message_types_by_name['SignatureRequestMessage'] = _SIGNATUREREQUESTMESSAGE
DESCRIPTOR.message_types_by_name['SignatureResponseMessage'] = _SIGNATURERESPONSEMESSAGE
DESCRIPTOR.message_types_by_name['ContractMessage'] = _CONTRACTMESSAGE
DESCRIPTOR.message_types_by_name['BlockRequestMessage'] = _BLOCKREQUESTMESSAGE
DESCRIPTOR.message_types_by_name['BlockMessage'] = _BLOCKMESSAGE
DESCRIPTOR.message_types_by_name['TraversalRequestMessage'] = _TRAVERSALREQUESTMESSAGE
DESCRIPTOR.message_types_by_name['TraversalResponseMessage'] = _TRAVERSALRESPONSEMESSAGE
DESCRIPTOR.message_types_by_name['Contract'] = _CONTRACT
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK

SignatureRequestMessage = _reflection.GeneratedProtocolMessageType('SignatureRequestMessage', (_message.Message,), dict(
  DESCRIPTOR = _SIGNATUREREQUESTMESSAGE,
  __module__ = 'conversion_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.SignatureRequestMessage)
  ))
_sym_db.RegisterMessage(SignatureRequestMessage)

SignatureResponseMessage = _reflection.GeneratedProtocolMessageType('SignatureResponseMessage', (_message.Message,), dict(
  DESCRIPTOR = _SIGNATURERESPONSEMESSAGE,
  __module__ = 'conversion_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.SignatureResponseMessage)
  ))
_sym_db.RegisterMessage(SignatureResponseMessage)

ContractMessage = _reflection.GeneratedProtocolMessageType('ContractMessage', (_message.Message,), dict(
  DESCRIPTOR = _CONTRACTMESSAGE,
  __module__ = 'conversion_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.ContractMessage)
  ))
_sym_db.RegisterMessage(ContractMessage)

BlockRequestMessage = _reflection.GeneratedProtocolMessageType('BlockRequestMessage', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKREQUESTMESSAGE,
  __module__ = 'conversion_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.BlockRequestMessage)
  ))
_sym_db.RegisterMessage(BlockRequestMessage)

BlockMessage = _reflection.GeneratedProtocolMessageType('BlockMessage', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKMESSAGE,
  __module__ = 'conversion_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.BlockMessage)
  ))
_sym_db.RegisterMessage(BlockMessage)

TraversalRequestMessage = _reflection.GeneratedProtocolMessageType('TraversalRequestMessage', (_message.Message,), dict(
  DESCRIPTOR = _TRAVERSALREQUESTMESSAGE,
  __module__ = 'conversion_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.TraversalRequestMessage)
  ))
_sym_db.RegisterMessage(TraversalRequestMessage)

TraversalResponseMessage = _reflection.GeneratedProtocolMessageType('TraversalResponseMessage', (_message.Message,), dict(
  DESCRIPTOR = _TRAVERSALRESPONSEMESSAGE,
  __module__ = 'conversion_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.TraversalResponseMessage)
  ))
_sym_db.RegisterMessage(TraversalResponseMessage)

Contract = _reflection.GeneratedProtocolMessageType('Contract', (_message.Message,), dict(
  DESCRIPTOR = _CONTRACT,
  __module__ = 'conversion_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.Contract)
  ))
_sym_db.RegisterMessage(Contract)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), dict(
  DESCRIPTOR = _BLOCK,
  __module__ = 'conversion_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.Block)
  ))
_sym_db.RegisterMessage(Block)


# @@protoc_insertion_point(module_scope)
